apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sample-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-sample-app
  template:
    metadata:
      labels:
        app: aws-sample-app
    spec:
      containers:
        - name: aws-sample
          image: aws-sample-new:0.0.3
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 8080
          imagePullPolicy: Never

