apiVersion: v1
kind: Pod
metadata:
  name: aws-sample-pod
spec:
  containers:
    - name: aws-sample
      image: aws-sample-new:0.0.3
      env:
        - name: AWS_PROFILE
          value: default
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
      ports:
        - containerPort: 8080
      imagePullPolicy: Never
  restartPolicy: Never

